# Generated by Django 4.1.2 on 2024-01-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="fcm_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
