# Generated by Django 4.1.2 on 2024-01-21 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_userprofile_fcm_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserwithdrawlTransactionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateTimeField(auto_created=True, auto_now=True)),
                ("kode", models.CharField(blank=True, max_length=255, null=True)),
                ("jumlah", models.FloatField(default=0.0)),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Request User"), (2, "Selesai Diproses")],
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
