# Generated by Django 4.1.2 on 2024-02-25 16:18

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_userprofileaddress_image_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofileaddress",
            name="image_profile",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="image_profile",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[1920, 1080],
                upload_to="profile_img/",
            ),
        ),
    ]
