# Generated by Django 4.1.2 on 2024-03-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_langsupport_is_active_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="langsupport",
            name="is_active_store",
            field=models.BooleanField(default=True),
        ),
    ]
