# Generated by Django 4.1.2 on 2024-03-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_alter_langsupport_is_active_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwithdrawltransactionrequest",
            name="kode",
            field=models.CharField(default="4MBE9", max_length=255),
        ),
    ]
