# Generated by Django 4.1.2 on 2024-03-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_alter_userwithdrawltransactionrequest_kode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwithdrawltransactionrequest",
            name="kode",
            field=models.CharField(default="NCLRI", max_length=255),
        ),
    ]
