# Generated by Django 4.1.2 on 2024-03-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0014_alter_userwithdrawltransactionrequest_kode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwithdrawltransactionrequest",
            name="kode",
            field=models.CharField(default="DB1J1", max_length=255),
        ),
    ]
