# Generated by Django 4.1.2 on 2024-03-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0020_alter_userwithdrawltransactionrequest_kode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwithdrawltransactionrequest",
            name="kode",
            field=models.CharField(default="4Y37K", max_length=255),
        ),
    ]
