# Generated by Django 4.1.2 on 2024-03-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0028_alter_userwithdrawltransactionrequest_kode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwithdrawltransactionrequest",
            name="kode",
            field=models.CharField(default="R5YZ8", max_length=255),
        ),
    ]
