# Generated by Django 4.1.2 on 2024-06-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_userappliedmember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithdrawltransactionrequest',
            name='kode',
            field=models.CharField(default='YLJ43', max_length=255),
        ),
    ]
