# Generated by Django 4.1.2 on 2024-07-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_alter_userwithdrawltransactionrequest_kode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappliedmember',
            name='name',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userwithdrawltransactionrequest',
            name='kode',
            field=models.CharField(default='QDW9Y', max_length=255),
        ),
    ]
