# Generated by Django 4.1.2 on 2024-07-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_userappliedmember_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithdrawltransactionrequest',
            name='kode',
            field=models.CharField(default='NP8F4', max_length=255),
        ),
    ]
