# Generated by Django 4.1.2 on 2024-07-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_alter_userwithdrawltransactionrequest_kode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappliedmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userappliedmember',
            name='nomor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userwithdrawltransactionrequest',
            name='kode',
            field=models.CharField(default='PHN0J', max_length=255),
        ),
    ]
