# Generated by Django 4.1.2 on 2024-07-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_userappliedmember_email_userappliedmember_nomor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithdrawltransactionrequest',
            name='kode',
            field=models.CharField(default='H7Y2Z', max_length=255),
        ),
    ]
