# Generated by Django 4.1.2 on 2024-07-29 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_alter_userwithdrawltransactionrequest_kode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bypass_verification_store', models.BooleanField(default=False)),
                ('kuota_withdrawl', models.IntegerField(default=0)),
                ('pajak_user', models.FloatField(default=0.0)),
                ('pajak_withdrawl', models.FloatField(default=0.0)),
                ('realtime_information', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='usersettingsmember',
            old_name='bypass_waiting',
            new_name='is_active_store',
        ),
        migrations.RenameField(
            model_name='usersettingsmember',
            old_name='quota_withdrawl',
            new_name='kuota',
        ),
        migrations.RemoveField(
            model_name='usersettingsmember',
            name='updated_information',
        ),
        migrations.AlterField(
            model_name='userwithdrawltransactionrequest',
            name='kode',
            field=models.CharField(default='YJ6HE', max_length=255),
        ),
        migrations.AddField(
            model_name='usersettingsmember',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.tier'),
        ),
    ]
