# Generated by Django 4.1.2 on 2024-03-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_expedisi"),
    ]

    operations = [
        migrations.AddField(
            model_name="expedisi",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
