# Generated by Django 4.1.2 on 2024-03-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_expedisi_url_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="expedisi",
            name="source_request",
            field=models.IntegerField(
                choices=[(1, "Raja Ongkir"), (2, "Biteship")], default=1
            ),
        ),
    ]
