# Generated by Django 4.1.2 on 2024-07-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_expedisi_source_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstore',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userstore',
            name='telpon',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
