# Generated by Django 4.1.2 on 2024-08-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_userstore_email_userstore_telpon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstore',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
