# Generated by Django 4.1.2 on 2023-12-24 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("produk", "0001_initial"),
        ("master", "0001_initial"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeaddresscartitem",
            name="userstore",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.userstore",
            ),
        ),
        migrations.AddField(
            model_name="storeaddresscartitem",
            name="village",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="master.village",
            ),
        ),
        migrations.AddField(
            model_name="produktransaksi",
            name="produk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="produk.produk"
            ),
        ),
        migrations.AddField(
            model_name="produkstok",
            name="produk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="produk.produk"
            ),
        ),
        migrations.AddField(
            model_name="produkstok",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.userstore"
            ),
        ),
        migrations.AddField(
            model_name="produkchartitem",
            name="kategori",
            field=models.ManyToManyField(to="produk.kategori"),
        ),
        migrations.AddField(
            model_name="produkchartitem",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.userstore"
            ),
        ),
        migrations.AddField(
            model_name="produkchartitem",
            name="tipe",
            field=models.ManyToManyField(blank=True, to="produk.tipeproduk"),
        ),
        migrations.AddField(
            model_name="produkchartitem",
            name="warna",
            field=models.ManyToManyField(blank=True, to="produk.warnaproduk"),
        ),
        migrations.AddField(
            model_name="produk",
            name="kategori",
            field=models.ManyToManyField(to="produk.kategori"),
        ),
        migrations.AddField(
            model_name="produk",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.userstore"
            ),
        ),
        migrations.AddField(
            model_name="produk",
            name="tipe",
            field=models.ManyToManyField(blank=True, to="produk.tipeproduk"),
        ),
        migrations.AddField(
            model_name="produk",
            name="warna",
            field=models.ManyToManyField(blank=True, to="produk.warnaproduk"),
        ),
        migrations.AddField(
            model_name="gambarproduk",
            name="produk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="produk.produk",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="produk.cart"
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="produk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="produk.produk"
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="produk_chart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="produk.produkchartitem",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="store_chart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="produk.storecartitem",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="user_chart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="produk.usercartitem",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="addressuserchartitem",
            name="distric",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="master.distric",
            ),
        ),
        migrations.AddField(
            model_name="addressuserchartitem",
            name="province",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="master.provinsi",
            ),
        ),
        migrations.AddField(
            model_name="addressuserchartitem",
            name="regency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="master.regency",
            ),
        ),
        migrations.AddField(
            model_name="addressuserchartitem",
            name="userprofile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="produk.usercartitem"
            ),
        ),
        migrations.AddField(
            model_name="addressuserchartitem",
            name="village",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="master.village",
            ),
        ),
    ]
