# Generated by Django 4.1.2 on 2024-01-06 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_expedisi'),
        ('produk', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='expoedisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.expedisi'),
        ),
    ]
