# Generated by Django 4.1.2 on 2024-01-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_cart_expoedisi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='expoedisi',
            new_name='expedisi',
        ),
    ]
