# Generated by Django 4.1.2 on 2024-02-25 16:27

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0006_gambarproduk_sortings'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='cross_boarder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gambarproduk',
            name='gambar',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='produk_image/'),
        ),
    ]
