# Generated by Django 4.1.2 on 2024-03-12 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produk", "0009_remove_produk_tipe_produk_tipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produkchartitem",
            name="tipe",
        ),
        migrations.AddField(
            model_name="produkchartitem",
            name="tipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="produk.tipeproduk",
            ),
        ),
    ]
