# Generated by Django 4.1.2 on 2024-03-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produk", "0010_remove_produkchartitem_tipe_produkchartitem_tipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produk",
            name="slug",
            field=models.TextField(blank=True, null=True),
        ),
    ]
