# Generated by Django 4.1.2 on 2024-03-21 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_alter_userwithdrawltransactionrequest_kode"),
        ("produk", "0011_alter_produk_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeskripsiProduk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deskripsi", models.TextField(blank=True, null=True)),
                (
                    "languange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.langsupport",
                    ),
                ),
            ],
        ),
    ]
