# Generated by Django 4.1.2 on 2024-03-21 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0006_alter_country_timezones"),
        ("produk", "0013_deskripsiproduk_produk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produk",
            name="negara",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="master.country",
            ),
        ),
    ]
