# Generated by Django 4.1.2 on 2024-03-21 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produk", "0014_alter_produk_negara"),
    ]

    operations = [
        migrations.AddField(
            model_name="ulasancart",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
