# Generated by Django 4.1.2 on 2023-12-24 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfigurationWebsite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key_pi", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "wallet_private_pi",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pajak_beli", models.FloatField(default=0)),
                ("pajak_withdrawl", models.FloatField(default=0)),
                ("koin_website", models.FloatField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Distric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="HistoriTampung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateTimeField(auto_now=True)),
                ("jumlah", models.FloatField(default=0)),
                ("success", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Provinsi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("nama", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SettingWebsite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama_pengaturan",
                    models.IntegerField(
                        choices=[
                            (1, "api_key"),
                            (2, "wallet_private"),
                            (3, "pajak_beli"),
                            (4, "pajak_withdrawl"),
                        ]
                    ),
                ),
                ("setting_value", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "district_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.distric"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Regency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "province_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.provinsi",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="distric",
            name="regency_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="master.regency"
            ),
        ),
    ]
