# Generated by Django 5.0.2 on 2024-03-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationwebsite",
            name="konfigurasi_firebase",
            field=models.FileField(blank=True, null=True, upload_to="konfigurasi/"),
        ),
    ]
