# Generated by Django 4.1.2 on 2024-03-21 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0004_region_subregion_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="region_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="master.region",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="subregion_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="master.subregion",
            ),
        ),
    ]
