# Generated by Django 4.1.2 on 2024-03-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0006_alter_country_timezones"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
