# Generated by Django 4.1.2 on 2024-03-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0007_country_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationwebsite",
            name="api_check_resi",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="configurationwebsite",
            name="url_check_resi",
            field=models.URLField(blank=True, null=True),
        ),
    ]
