# Generated by Django 4.1.2 on 2024-03-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0008_configurationwebsite_api_check_resi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationwebsite",
            name="api_biteship",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
