# Generated by Django 4.1.2 on 2024-06-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_configurationwebsite_api_biteship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='timezones',
            field=models.TextField(blank=True, default=[], null=True),
        ),
    ]
