# Generated by Django 4.1.2 on 2024-06-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_configurationwebsite_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationwebsite',
            name='bypass_expedisi',
            field=models.BooleanField(default=False),
        ),
    ]
