# Generated by Django 4.1.2 on 2024-03-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0004_alter_contenttranslate_tag_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pengumuman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_pengumuman", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Pengumuman Website",
                "verbose_name_plural": "Pengumuman Website",
            },
        ),
    ]
