# Generated by Django 4.1.2 on 2024-03-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0005_pengumuman"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_for",
                    models.IntegerField(
                        choices=[(1, "Aggrement")], default=1, unique=True
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Page",
            },
        ),
    ]
