# Generated by Django 4.1.2 on 2024-03-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0006_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="page_for",
            field=models.IntegerField(
                choices=[(1, "Aggrement"), (2, "Privacy and Policy")],
                default=1,
                unique=True,
            ),
        ),
    ]
